[package]
#[allow(non_snake_case)]
name = "open-wave"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.5"
dotenvy = "0.15"


[build-dependencies]
slint-build = "1.5"
